version: '3'
services:
  nginx:      
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: nginx_web
    ports:
      - "80:80"      
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net1
  api:      
    build:
      context: ./store_api
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "3000:3000"      
    volumes:
      - ./store_api/:/go/src
    networks:
      - net1
  store:      
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: store_web
    ports:
      - "3333:80"      
    volumes:
      - ./build/web:/usr/share/nginx/html 
      - ./docker/store.nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net1
networks:
  net1:
    driver: bridge