name: store_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  auto_route: ^3.2.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hooks_riverpod: ^1.0.3

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4
  pedantic_mono: null

flutter:
  uses-material-design: true
